// Venue and sport type definitions
// These match the Prisma schema but are maintained separately for better control

export enum SportType {
  BADMINTON = "BADMINTON",
  TENNIS = "TENNIS",
  SQUASH = "SQUASH",
  BASKETBALL = "BASKETBALL",
  FOOTBALL = "FOOTBALL",
  CRICKET = "CRICKET",
  TABLE_TENNIS = "TABLE_TENNIS",
  VOLLEYBALL = "VOLLEYBALL",
}

export enum VenueType {
  INDOOR = "INDOOR",
  OUTDOOR = "OUTDOOR",
  MIXED = "MIXED",
}

export enum BookingStatus {
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
}

export enum MatchStatus {
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum FacilityStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum UserRole {
  USER = "USER",
  FACILITY_OWNER = "FACILITY_OWNER",
  ADMIN = "ADMIN",
}

export enum WaitlistStatus {
  WAITING = "WAITING",
  PROMOTED = "PROMOTED",
  EXPIRED = "EXPIRED",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  SUCCESSFUL = "SUCCESSFUL",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
  CANCELLED = "CANCELLED",
}

export enum BookingReservationStatus {
  RESERVED = "RESERVED",
  CONFIRMED = "CONFIRMED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
}

export enum ReportType {
  FACILITY_INAPPROPRIATE_CONTENT = "FACILITY_INAPPROPRIATE_CONTENT",
  FACILITY_FALSE_INFORMATION = "FACILITY_FALSE_INFORMATION",
  FACILITY_SAFETY_CONCERN = "FACILITY_SAFETY_CONCERN",
  USER_HARASSMENT = "USER_HARASSMENT",
  USER_INAPPROPRIATE_BEHAVIOR = "USER_INAPPROPRIATE_BEHAVIOR",
  USER_SPAM = "USER_SPAM",
  OTHER = "OTHER",
}

export enum ReportStatus {
  PENDING = "PENDING",
  UNDER_REVIEW = "UNDER_REVIEW",
  RESOLVED = "RESOLVED",
  DISMISSED = "DISMISSED",
}
